
-- ============================================================
-- Course      : C11665 - DPR400210 Database Programming
-- Project     : Hospital Management System
-- Assignment  : Group Assignment I
-- File        : part_a_ctes.sql
-- Database    : PostgreSQL
-- ============================================================

/*
==============================================================
PART A: COMMON TABLE EXPRESSIONS (CTEs)
==============================================================

This file demonstrates five different Common Table Expressions
(CTEs) using the Hospital Management System database.

CTEs included:

1. Simple CTE
2. Multiple CTEs
3. Recursive CTE
4. Aggregation CTE
5. JOIN CTE

==============================================================
*/


-- ============================================================
-- CTE 1 : SIMPLE CTE
-- ============================================================
-- Business Question:
-- Which completed appointments have a bill greater than 400?

WITH HighValueAppointments AS
(
    SELECT
        appointment_id,
        patient_id,
        doctor_id,
        bill_amount
    FROM Appointments
    WHERE bill_amount > 400
)

SELECT *
FROM HighValueAppointments
ORDER BY bill_amount DESC;



-- ============================================================
-- CTE 2 : MULTIPLE CTEs
-- ============================================================
-- Business Question:
-- What is the total revenue generated by each doctor?

WITH DoctorRevenue AS
(
    SELECT
        doctor_id,
        SUM(bill_amount) AS total_revenue
    FROM Appointments
    GROUP BY doctor_id
),

DoctorInformation AS
(
    SELECT
        doctor_id,
        first_name,
        last_name,
        specialization
    FROM Doctors
)

SELECT
    d.doctor_id,
    d.first_name,
    d.last_name,
    d.specialization,
    r.total_revenue
FROM DoctorInformation d
JOIN DoctorRevenue r
ON d.doctor_id = r.doctor_id
ORDER BY total_revenue DESC;



-- ============================================================
-- CTE 3 : RECURSIVE CTE
-- ============================================================
-- Business Question:
-- Display the reporting hierarchy of doctors.

WITH RECURSIVE DoctorHierarchy AS
(
    SELECT
        doctor_id,
        first_name,
        last_name,
        supervisor_id,
        1 AS level
    FROM Doctors
    WHERE supervisor_id IS NULL

    UNION ALL

    SELECT
        d.doctor_id,
        d.first_name,
        d.last_name,
        d.supervisor_id,
        dh.level + 1
    FROM Doctors d
    INNER JOIN DoctorHierarchy dh
        ON d.supervisor_id = dh.doctor_id
)

SELECT
    level,
    doctor_id,
    first_name,
    last_name,
    supervisor_id
FROM DoctorHierarchy
ORDER BY level, doctor_id;



-- ============================================================
-- CTE 4 : AGGREGATION CTE
-- ============================================================
-- Business Question:
-- How much has each patient spent in total?

WITH PatientSpending AS
(
    SELECT
        patient_id,
        COUNT(*) AS total_visits,
        SUM(bill_amount) AS total_spent,
        AVG(bill_amount) AS average_bill
    FROM Appointments
    GROUP BY patient_id
)

SELECT
    p.patient_id,
    p.first_name,
    p.last_name,
    ps.total_visits,
    ps.total_spent,
    ROUND(ps.average_bill,2) AS average_bill
FROM Patients p
JOIN PatientSpending ps
ON p.patient_id = ps.patient_id
ORDER BY total_spent DESC;



-- ============================================================
-- CTE 5 : JOIN CTE
-- ============================================================
-- Business Question:
-- Display complete appointment information.

WITH AppointmentReport AS
(
    SELECT

        a.appointment_id,

        p.first_name || ' ' || p.last_name
            AS patient,

        d.first_name || ' ' || d.last_name
            AS doctor,

        d.specialization,

        a.appointment_date,

        a.status,

        a.bill_amount

    FROM Appointments a

    JOIN Patients p
        ON a.patient_id = p.patient_id

    JOIN Doctors d
        ON a.doctor_id = d.doctor_id
)

SELECT *
FROM AppointmentReport
ORDER BY appointment_date;



-- ============================================================
-- END OF PART A
-- ============================================================
